# Generated by Django 5.2.6 on 2025-10-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_dealership'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealership',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
